### ISSUE TITLE
How to run mqttexample

### ISSUE THREAD

**Issue by borch84** [aws-samples/aws-iot-examples#6]
Hi! I am new to aws-iot-sdk-js sdk, I would like to implement the **mqttSample**, but it is not clear to me how I can start the example code from my computer?
I executed: 
```
git clone https://github.com/aws-samples/aws-iot-examples.git
cd aws-iot-example/mqttSample
node start
```
But I am getting this error:

```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/home/borch/Documents/JavaScript-Apps/aws-iot-examples/mqttSample/start'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

```
Appreciate anyone could point me to the correct direction. Thank you.

**Comment by borch84** [comment]
Hi I was able to run the example and see messages from my esp32 device being published to a mqtt topic.
After I cloned the repository I did the following:
cd mqttSample
```
npm install
npm install -g http-server
http-server
```
